### ISSUE TITLE
Colouring of sample of interest in multiQC plots

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#122]
https://umccr.slack.com/archives/C016A5BSKRC/p1663039785236699

```
I was also wondering if it is possible to color the sample of interest differently so it stands out more compared to the reference samples, sometimes it can be hard to locate the right ones.

For that I was referring to color for all the graphs in the mulqiQC report.
At the moment with most of the plots read 1 and 2 for the tumour sample is colored blue and black respectively, they can kind of get lost when the lines are tight. If we could have them both colored something like black or something that stand out it would be easier to see.

For example in this plot I couldn’t easily find the reads from the tumor sample, there are two blue lines, one for reference and one for tumor sample, they are really tight and I couldn’t distinguish them.

For example GC Content Mean Quality Scores plot for [SBJ02805 ](https://data.umccr.org/subjects/SBJ02805)).
```

**Comment by alexiswl** [comment]
This isn't an easy process to complete automatically, I've linked two relevant issues below:
* https://github.com/ewels/MultiQC/issues/132
* https://github.com/ewels/MultiQC/issues/1090

Even though extensive work has been done in the [customisation help page](https://github.com/ewels/MultiQC/blob/master/docs/customisation.md), sample highlighting is not yet possible.

However, this is done in umccrise though.  

For example:

![image](https://user-images.githubusercontent.com/8197659/190276849-c2066d7b-920c-4b9c-ad9c-0fd3a59424a0.png)

Where all reference samples are greyed out by default. 

This works by inserting a header into the top of the multiqc html: See this html script chunk below -
https://github.com/umccr/umccrise/blob/master/umccrise/multiqc/templates/umccr/header.html#L68-L87

The highlight_regex is also set to true in the configuration.  
https://github.com/umccr/umccrise/blob/master/umccrise/multiqc/multiqc_config.yaml#L128

@scwatts may be able to assist you further, since I think what you're after here is much simpler than what is required in umccrise.

**Comment by ohofmann** [comment]
I did not know this was handled through changing the HTML. Ooookay.

**Comment by scwatts** [comment]
Unfortunately no easy way to do this in MultiQC as @alexiswl pointed out, and I think this is as straightforward as it gets despite having to edit the DOM: sample selection, highlighting, and ordering.

I'm not familiar with the use of MultiQC in the WTS pipeline but I can't see this being simplified any further. Initial approach here would be to introduce the `umccr` MultiQC template used by Umccrise into the WTS workflow - logistics of this are unclear to me.

If that is pursued it would be another reason to eventually consolidate UMCCR MultiQC resources/code in one place for maintenance, documentation, ops purposes.

**Comment by skanwal** [comment]
I had this discussion with Stephen previously (Thanks @scwatts for writing it down here). There isn't seem to be a straightforward way via multiqc config/setting to achieve this. 
One to discuss in the lab or bioinfo meeting.
